from __future__ import annotations

import json
from html import escape
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from ppt_agent.domain.models import DeckIntent, PptSpec
from ppt_agent.runtime.harness.artifacts import stage_dir
from ppt_agent.runtime.harness.events import append_event
from ppt_agent.runtime.harness.gates import GateResult, run_quality_gates
from ppt_agent.runtime.harness.manifest import (
    STAGE_ORDER,
    HarnessManifest,
    HarnessStage,
    load_manifest,
    save_manifest,
    update_stage,
    write_json,
)


APPROVAL_STAGES = {"plan_confirm", "build_confirm"}
PREVIEW_STAGE = "page_preview"
PASSING_STATUSES = {"passed", "completed", "approved", "skipped"}
REGENERABLE_STAGES = {
    "content",
    "design_chart",
    "slides_ir",
    "qa",
    "repair",
    "page_design",
    "renderer_engineer",
    "page_generator",
    "page_preview",
    "render_review",
}


class HarnessAction(BaseModel):
    action: Literal["continue", "waiting_approval", "needs_rework", "failed", "completed"]
    task_id: str
    stage_id: str | None = None
    message: str
    manifest: dict[str, Any] = Field(default_factory=dict)


class HarnessRunner:
    """Small state machine for archived Harness tasks.

    The current multi-agent pipeline still performs the expensive generation. This
    runner controls already archived tasks: it creates human confirmation points,
    reruns deterministic gates, writes preview artifacts, and records decisions.
    """

    def __init__(self, task_dir: Path) -> None:
        self.task_dir = task_dir

    def status(self) -> HarnessAction:
        manifest = self._load_manifest()
        return self._action("continue", manifest, manifest.current_stage, "task loaded")

    def run_until_blocked(self, *, auto_rework: bool = False, max_rework: int = 1) -> HarnessAction:
        manifest = self._load_manifest()
        rework_attempts: dict[str, int] = {}
        while True:
            next_stage = self._next_stage(manifest)
            if next_stage is None:
                manifest.status = "completed"
                manifest.current_stage = None
                save_manifest(self.task_dir, manifest)
                append_event(self.task_dir, "task.completed")
                return self._action("completed", manifest, None, "task completed")

            if next_stage.id in APPROVAL_STAGES:
                return self._ensure_waiting_approval(manifest, next_stage)

            if next_stage.id == PREVIEW_STAGE:
                self._write_page_previews(manifest, next_stage)
                manifest = load_manifest(self.task_dir)
                continue

            if next_stage.status in {"invalidated", "needs_rework", "rejected"} and next_stage.id in REGENERABLE_STAGES:
                self.regenerate_from(next_stage.id)
                manifest = self._load_manifest()
                continue

            gate = self.run_stage_gate(next_stage.id)
            manifest = load_manifest(self.task_dir)
            if gate.status == "failed":
                append_event(self.task_dir, "stage.failed", stage_id=next_stage.id, payload=gate.model_dump(mode="json"))
                return self._action("failed", manifest, next_stage.id, f"{next_stage.id} failed quality gates")
            if gate.status == "needs_rework":
                if auto_rework and next_stage.id in REGENERABLE_STAGES and rework_attempts.get(next_stage.id, 0) < max_rework:
                    rework_attempts[next_stage.id] = rework_attempts.get(next_stage.id, 0) + 1
                    append_event(
                        self.task_dir,
                        "stage.auto_rework",
                        stage_id=next_stage.id,
                        payload={"attempt": rework_attempts[next_stage.id], "max_rework": max_rework},
                    )
                    self.regenerate_from(next_stage.id)
                    manifest = self._load_manifest()
                    continue
                append_event(self.task_dir, "stage.needs_rework", stage_id=next_stage.id, payload=gate.model_dump(mode="json"))
                return self._action("needs_rework", manifest, next_stage.id, f"{next_stage.id} needs rework")
            append_event(self.task_dir, "stage.continued", stage_id=next_stage.id)

    def regenerate_from(self, stage_id: str) -> HarnessAction:
        if stage_id not in REGENERABLE_STAGES:
            raise ValueError(f"{stage_id} cannot be regenerated by HarnessRunner")
        manifest = self._load_manifest()
        if not manifest.stage(stage_id):
            raise ValueError(f"unknown stage: {stage_id}")
        append_event(self.task_dir, "task.regenerate_started", stage_id=stage_id)
        artifacts = self._load_regeneration_context(manifest)
        start_index = STAGE_ORDER.index(stage_id)

        state = self._regeneration_state(manifest, artifacts)

        if start_index <= STAGE_ORDER.index("content"):
            state = self._pipeline_funcs()["content_node"](state)
            artifacts["content"] = state["content"]
            self._record_stage(manifest, "content", artifacts["content"])
        if start_index <= STAGE_ORDER.index("design_chart"):
            state = self._pipeline_funcs()["design_chart_node"](state)
            artifacts["design_chart"] = state["design_chart"]
            self._record_stage(manifest, "design_chart", artifacts["design_chart"])
        if start_index <= STAGE_ORDER.index("slides_ir"):
            state.update({"content": artifacts["content"], "design_chart": artifacts["design_chart"]})
            state = self._pipeline_funcs()["supervisor_merge_node"](state)
            artifacts["slides_ir"] = state["slides_ir"]
            self._record_stage(manifest, "slides_ir", artifacts["slides_ir"])
        if start_index <= STAGE_ORDER.index("qa"):
            state.update({"slides_ir": artifacts["slides_ir"]})
            state = self._pipeline_funcs()["qa_node"](state)
            artifacts["qa"] = state["review_report"]
            self._record_stage(manifest, "qa", artifacts["qa"])
        if start_index <= STAGE_ORDER.index("repair"):
            qa_report = self._pipeline_funcs()["PipelineQaReport"].model_validate(artifacts["qa"])
            if not qa_report.ok:
                state.update({"slides_ir": artifacts["slides_ir"], "review_report": artifacts["qa"]})
                state = self._pipeline_funcs()["supervisor_repair_node"](state)
                artifacts["repair"] = state["slides_ir"]
            else:
                artifacts["repair"] = artifacts["slides_ir"]
            artifacts["slides_ir"] = artifacts["repair"]
            self._record_stage(manifest, "repair", artifacts["repair"])
        if start_index <= STAGE_ORDER.index("page_design"):
            state.update({"slides_ir": artifacts["slides_ir"]})
            state = self._pipeline_funcs()["page_designer_node"](state)
            artifacts["page_design"] = state["page_design"]
            self._record_stage(manifest, "page_design", artifacts["page_design"])
        if start_index <= STAGE_ORDER.index("renderer_engineer"):
            state.update({"slides_ir": artifacts["slides_ir"], "page_design": artifacts["page_design"]})
            state = self._pipeline_funcs()["renderer_engineer_node"](state)
            artifacts["renderer_engineer"] = state["renderer_engineer_report"]
            self._record_stage(manifest, "renderer_engineer", artifacts["renderer_engineer"])
        if start_index <= STAGE_ORDER.index("page_generator"):
            state.update(
                {
                    "slides_ir": artifacts["slides_ir"],
                    "page_design": artifacts["page_design"],
                    "renderer_engineer_report": artifacts["renderer_engineer"],
                }
            )
            state = self._pipeline_funcs()["page_generator_node"](state)
            artifacts["page_generator"] = state["spec"]
            output_path = self._record_stage(manifest, "page_generator", artifacts["page_generator"])
            manifest.outputs["ppt_spec"] = str(output_path.relative_to(self.task_dir))
        if start_index <= STAGE_ORDER.index("page_preview"):
            self._write_page_previews(manifest, self._require_stage(manifest, "page_preview"))
            manifest = self._load_manifest()
        if start_index <= STAGE_ORDER.index("render_review"):
            state.update(
                {
                    "slides_ir": artifacts["slides_ir"],
                    "page_design": artifacts["page_design"],
                    "renderer_engineer_report": artifacts["renderer_engineer"],
                    "spec": artifacts["page_generator"],
                }
            )
            state = self._pipeline_funcs()["render_review_node"](state)
            artifacts["render_review"] = state["render_review_report"]
            self._record_stage(manifest, "render_review", artifacts["render_review"])

        build_confirm = manifest.stage("build_confirm")
        if build_confirm and build_confirm.status not in {"approved", "waiting_approval"}:
            build_confirm.status = "waiting_approval"
            manifest.status = "waiting_approval"
            manifest.current_stage = "build_confirm"
            save_manifest(self.task_dir, manifest)
        append_event(self.task_dir, "task.regenerate_completed", stage_id=stage_id)
        return self._action("continue", manifest, stage_id, f"regenerated from {stage_id}")

    def approve(self, stage_id: str, *, note: str = "approved") -> HarnessAction:
        manifest = self._load_manifest()
        stage = self._require_stage(manifest, stage_id)
        if stage_id not in APPROVAL_STAGES:
            raise ValueError(f"{stage_id} is not an approval stage")
        if stage.status not in {"waiting_approval", "rejected"}:
            raise ValueError(f"{stage_id} is not waiting for approval")
        stage.status = "approved"
        stage.metrics["approval_note"] = note
        stage.invalidated_by = None
        manifest.current_stage = stage_id
        self._refresh_and_save(manifest)
        append_event(self.task_dir, "stage.approved", stage_id=stage_id, payload={"note": note})
        return self.run_until_blocked()

    def reject(self, stage_id: str, *, reason: str) -> HarnessAction:
        manifest = self._load_manifest()
        stage = self._require_stage(manifest, stage_id)
        if stage_id not in APPROVAL_STAGES:
            raise ValueError(f"{stage_id} is not an approval stage")
        stage.status = "rejected"
        stage.invalidated_by = reason
        stage.issues = [{"severity": "warning", "rule": "manual_rejection", "message": reason}]
        manifest.status = "rejected"
        manifest.current_stage = stage_id
        save_manifest(self.task_dir, manifest)
        append_event(self.task_dir, "stage.rejected", stage_id=stage_id, payload={"reason": reason})
        return self._action("needs_rework", manifest, stage_id, f"{stage_id} rejected: {reason}")

    def run_stage_gate(self, stage_id: str) -> GateResult:
        manifest = self._load_manifest()
        stage = self._require_stage(manifest, stage_id)
        payload = self._load_stage_payload(stage)
        gate = run_quality_gates(stage_id, payload)
        eval_path = self.task_dir / (stage.eval_path or f"stages/{stage_id}/eval.json")
        write_json(eval_path, gate.model_dump(mode="json"))
        status = gate.status
        if status == "passed":
            status = "passed"
        update_stage(
            self.task_dir,
            manifest,
            stage_id,
            status=status,
            eval_path=str(eval_path),
            issues=[issue.model_dump(mode="json") for issue in gate.issues],
            metrics=gate.metrics | {"gate_score": gate.score, "gate_next_action": gate.next_action},
        )
        return gate

    def _record_stage(self, manifest: HarnessManifest, stage_id: str, payload: dict[str, Any] | list[Any]) -> Path:
        stage = self._require_stage(manifest, stage_id)
        directory = self._stage_directory(stage_id, stage)
        output_path = write_json(directory / "output.json", payload)
        gate = run_quality_gates(stage_id, payload)
        eval_path = write_json(directory / "eval.json", gate.model_dump(mode="json"))
        status_path = write_json(
            directory / "status.json",
            {
                "stage_id": stage_id,
                "status": gate.status,
                "next_action": gate.next_action,
                "regenerated": True,
            },
        )
        update_stage(
            self.task_dir,
            manifest,
            stage_id,
            status=gate.status,
            output_path=str(output_path),
            eval_path=str(eval_path),
            status_path=str(status_path),
            issues=[issue.model_dump(mode="json") for issue in gate.issues],
            metrics=gate.metrics | {"gate_score": gate.score, "gate_next_action": gate.next_action, "regenerated": True},
        )
        append_event(self.task_dir, "stage.regenerated", stage_id=stage_id, payload={"status": gate.status, "score": gate.score})
        return output_path

    def _ensure_waiting_approval(self, manifest: HarnessManifest, stage: HarnessStage) -> HarnessAction:
        if stage.status == "approved":
            return self._action("continue", manifest, stage.id, f"{stage.id} already approved")
        stage.status = "waiting_approval"
        stage.metrics.setdefault("approval_type", stage.id)
        manifest.status = "waiting_approval"
        manifest.current_stage = stage.id
        save_manifest(self.task_dir, manifest)
        append_event(self.task_dir, "stage.waiting_approval", stage_id=stage.id)
        return self._action("waiting_approval", manifest, stage.id, f"{stage.id} is waiting for approval")

    def _write_page_previews(self, manifest: HarnessManifest, stage: HarnessStage) -> None:
        spec_path = manifest.outputs.get("ppt_spec")
        slides = []
        if spec_path and (self.task_dir / spec_path).exists():
            spec = json.loads((self.task_dir / spec_path).read_text(encoding="utf-8-sig"))
            slides = spec.get("slides") or []
        preview_dir = self.task_dir / "previews"
        preview_dir.mkdir(parents=True, exist_ok=True)
        index_path = preview_dir / "index.json"
        preview_items = []
        for index, slide in enumerate(slides, start=1):
            item_path = preview_dir / f"slide_{index:03d}.json"
            html_path = preview_dir / f"slide_{index:03d}.html"
            item = {
                "slide_no": index,
                "title": slide.get("title"),
                "message": slide.get("message"),
                "layout": slide.get("layout"),
                "notes": slide.get("speaker_notes") or slide.get("notes"),
            }
            write_json(item_path, item)
            html_path.write_text(self._slide_preview_html(item), encoding="utf-8")
            preview_items.append(
                {
                    "slide_no": index,
                    "path": str(item_path.relative_to(self.task_dir)),
                    "html_path": str(html_path.relative_to(self.task_dir)),
                    "title": item.get("title"),
                }
            )
        write_json(index_path, {"slides": preview_items})
        manifest.outputs["page_preview"] = str(index_path.relative_to(self.task_dir))
        update_stage(
            self.task_dir,
            manifest,
            PREVIEW_STAGE,
            status="passed",
            output_path=str(index_path),
            metrics={"preview_count": len(preview_items)},
        )
        append_event(self.task_dir, "stage.preview_written", stage_id=stage.id, payload={"preview_count": len(preview_items)})

    @staticmethod
    def _slide_preview_html(slide: dict[str, Any]) -> str:
        title = escape(str(slide.get("title") or "Untitled"))
        message = escape(str(slide.get("message") or ""))
        layout = escape(str(slide.get("layout") or "default"))
        notes = escape(str(slide.get("notes") or ""))
        return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <style>
    body {{ margin: 0; background: #f3f4f6; color: #111827; font-family: Arial, "Microsoft YaHei", sans-serif; }}
    .slide {{ width: min(1120px, calc(100vw - 32px)); aspect-ratio: 16 / 9; margin: 16px auto; background: #fff; border: 1px solid #d1d5db; box-shadow: 0 10px 30px rgba(15, 23, 42, .12); padding: 56px; display: flex; flex-direction: column; gap: 24px; }}
    .meta {{ color: #64748b; font-size: 14px; text-transform: uppercase; letter-spacing: .08em; }}
    h1 {{ margin: 0; font-size: 44px; line-height: 1.12; letter-spacing: 0; }}
    .message {{ font-size: 24px; line-height: 1.45; max-width: 880px; }}
    .notes {{ margin-top: auto; border-top: 1px solid #e5e7eb; padding-top: 16px; color: #475569; font-size: 16px; line-height: 1.5; }}
  </style>
</head>
<body>
  <main class="slide">
    <div class="meta">Slide {slide.get("slide_no")} / {layout}</div>
    <h1>{title}</h1>
    <section class="message">{message}</section>
    <section class="notes">{notes}</section>
  </main>
</body>
</html>
"""

    def _load_stage_payload(self, stage: HarnessStage) -> dict[str, Any] | list[Any] | None:
        for relative in (stage.output_path, stage.input_path):
            if not relative:
                continue
            path = self.task_dir / relative
            if path.exists() and path.is_file():
                return json.loads(path.read_text(encoding="utf-8-sig"))
        return {}

    def _load_payload_by_stage(self, manifest: HarnessManifest, stage_id: str) -> Any:
        stage = self._require_stage(manifest, stage_id)
        return self._load_stage_payload(stage) or {}

    def _load_regeneration_context(self, manifest: HarnessManifest) -> dict[str, Any]:
        brief_outline = self._load_payload_by_stage(manifest, "brief_outline")
        if not isinstance(brief_outline, dict):
            raise ValueError("brief_outline payload is missing")
        context = {
            "brief": brief_outline.get("brief") or brief_outline,
            "outline": brief_outline.get("outline") or {},
            "content": self._load_payload_by_stage(manifest, "content"),
            "design_chart": self._load_payload_by_stage(manifest, "design_chart"),
            "slides_ir": self._load_payload_by_stage(manifest, "slides_ir"),
            "qa": self._load_payload_by_stage(manifest, "qa"),
            "repair": self._load_payload_by_stage(manifest, "repair"),
            "page_design": self._load_payload_by_stage(manifest, "page_design"),
            "renderer_engineer": self._load_payload_by_stage(manifest, "renderer_engineer"),
            "page_generator": self._load_payload_by_stage(manifest, "page_generator"),
        }
        if not context["brief"] or not context["outline"]:
            raise ValueError("brief and outline are required to regenerate downstream stages")
        return context

    def _stage_directory(self, stage_id: str, stage: HarnessStage) -> Path:
        for relative in (stage.output_path, stage.input_path, stage.eval_path, stage.status_path):
            if relative:
                return (self.task_dir / relative).parent
        return stage_dir(self.task_dir, STAGE_ORDER.index(stage_id) + 1, stage_id)

    def _intent_from_manifest(self, manifest: HarnessManifest) -> DeckIntent:
        brief_payload = self._load_payload_by_stage(manifest, "brief_outline")
        brief = brief_payload.get("brief") if isinstance(brief_payload, dict) else {}
        return DeckIntent(
            topic=manifest.topic,
            audience=(brief or {}).get("audience"),
            applied_skills=list((manifest.metadata.get("skill_assignments") or {}).keys()),
        )

    def _regeneration_state(self, manifest: HarnessManifest, artifacts: dict[str, Any]) -> dict[str, Any]:
        intent = self._intent_from_manifest(manifest)
        return {
            "intent": intent.model_dump(mode="json"),
            "task_dir": str(self.task_dir),
            "brief": artifacts["brief"],
            "outline": artifacts["outline"],
            "content": artifacts.get("content") or {},
            "design_chart": artifacts.get("design_chart") or {},
            "slides_ir": artifacts.get("slides_ir") or {},
            "review_report": artifacts.get("qa") or {},
            "page_design": artifacts.get("page_design") or {},
            "renderer_engineer_report": artifacts.get("renderer_engineer") or {},
            "spec": artifacts.get("page_generator") or {},
            "transitions": [],
            "llm_config": self._pipeline_funcs()["load_agent_llm_config"](self._workspace_root()),
            "skill_assignments": self._pipeline_funcs()["assign_skills_to_agents"](self._workspace_root()),
        }

    @staticmethod
    def _pipeline_funcs() -> dict[str, Any]:
        from ppt_agent.runtime import multi_agent_pipeline as pipeline

        return {
            "PipelineQaReport": pipeline.PipelineQaReport,
            "assign_skills_to_agents": pipeline.assign_skills_to_agents,
            "content_node": pipeline.content_node,
            "design_chart_node": pipeline.design_chart_node,
            "supervisor_merge_node": pipeline.supervisor_merge_node,
            "qa_node": pipeline.qa_node,
            "supervisor_repair_node": pipeline.supervisor_repair_node,
            "page_designer_node": pipeline.page_designer_node,
            "renderer_engineer_node": pipeline.renderer_engineer_node,
            "page_generator_node": pipeline.page_generator_node,
            "render_review_node": pipeline.render_review_node,
            "load_agent_llm_config": pipeline.load_agent_llm_config,
        }

    def _workspace_root(self) -> Path:
        try:
            return self.task_dir.parents[2]
        except IndexError:
            return Path.cwd()

    def _next_stage(self, manifest: HarnessManifest) -> HarnessStage | None:
        for stage_id in STAGE_ORDER:
            stage = manifest.stage(stage_id)
            if stage is None:
                continue
            if stage.status not in PASSING_STATUSES:
                return stage
        return None

    def _require_stage(self, manifest: HarnessManifest, stage_id: str) -> HarnessStage:
        stage = manifest.stage(stage_id)
        if stage is None:
            raise ValueError(f"unknown stage: {stage_id}")
        return stage

    def _refresh_and_save(self, manifest: HarnessManifest) -> None:
        # update_stage owns the private resume refresh; use a harmless update for consistency.
        current = manifest.current_stage
        if current:
            update_stage(self.task_dir, manifest, current, status=self._require_stage(manifest, current).status)
        else:
            save_manifest(self.task_dir, manifest)

    def _load_manifest(self) -> HarnessManifest:
        manifest = load_manifest(self.task_dir)
        existing = {stage.id for stage in manifest.stages}
        changed = False
        for stage_id in STAGE_ORDER:
            if stage_id not in existing:
                manifest.stages.append(HarnessStage(id=stage_id, name=stage_id.replace("_", " ").title()))
                changed = True
        if changed:
            manifest.stages.sort(key=lambda stage: STAGE_ORDER.index(stage.id) if stage.id in STAGE_ORDER else len(STAGE_ORDER))
            save_manifest(self.task_dir, manifest)
        return manifest

    def _action(self, action: Literal["continue", "waiting_approval", "needs_rework", "failed", "completed"], manifest: HarnessManifest, stage_id: str | None, message: str) -> HarnessAction:
        return HarnessAction(
            action=action,
            task_id=manifest.task_id,
            stage_id=stage_id,
            message=message,
            manifest=manifest.model_dump(mode="json"),
        )
